Added anyHandler to bot.hh
DiscordPP/discordpp pull request #31
Opened 2020-12-22 20:46 UTC by niansa

Created anyHandler in bot object

2020-12-22 20:52 UTC, niansa commented
Idk why my second commit reverted the first one. Had to revert the revert in a third commit.

2020-12-22 21:17 UTC, niansa commented
1 second this stopped working when I hit reconfigure on my IDE :thinking:

2020-12-22 21:18 UTC, niansa commented
Ah, forgot to commit a file

2020-12-22 21:20 UTC, niansa commented
Fixed

2020-12-22 21:53 UTC, niansa commented
Please do not merge yet, I consider changing later.

2020-12-23 12:07 UTC, niansa commented
Okay should be good to merge now!

2021-01-15 18:51 UTC, UndarkAido requested changes

2021-01-15 18:51 UTC, UndarkAido commented on discordpp/botStruct.hh
> +    handleAnyEvent anyHandler = nullptr;
Should be an `std::vector` to match the `std::multimap`

2021-02-28 16:18 UTC, niansa reviewed
Yep

2021-03-06 07:11 UTC, UndarkAido commented
I'm still conflicted as to whether or not this is a good idea. Could you show me the code where you use this?

2021-03-24 11:24 UTC, niansa commented
> I'm still conflicted as to whether or not this is a good idea. Could you show me the code where you use this?

Logging intents, as example.

2021-03-24 16:51 UTC, UndarkAido commented
This PR will be implemented as a plugin

2021-03-24 16:51 UTC, closed without merging